import { AI_MEMBERS_FORM_DATA,FORM_METADATA } from "./form-metadata"
import { LOCAL_STORAGE_LOADING_STATE } from "./local-storage-loading-state"
const TIME_INTERVAL = 4000
const THREE_SECOND_TIME_INTERVAL = 3000



export {
    AI_MEMBERS_FORM_DATA,
    FORM_METADATA,
    LOCAL_STORAGE_LOADING_STATE,
    TIME_INTERVAL,
    THREE_SECOND_TIME_INTERVAL
}