import { AI_MEMBERS_FORM_DATA,FORM_METADATA } from "./form-metadata"
const TIME_INTERVAL = 4000
const THREE_SECOND_TIME_INTERVAL = 3000


export {
    AI_MEMBERS_FORM_DATA,
    FORM_METADATA,
    TIME_INTERVAL,
    THREE_SECOND_TIME_INTERVAL
}